### ISSUE TITLE
.prototype not mentioned in reading

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/prototypal-oo-reviewing-javascript-prototypal-inheritance-quiz#2]
The correct answer to question number four
`"Dog.prototype.bark =  () => console.log(`${this.name} says bark`)"`
mentions `.prototype`, which did not come up in the reading.

**Comment by sgharms** [comment]
@kjgenevieve 

This might be more of a classroom issue, but the materials that cover this concept are located in the following source labs:

https://github.com/learn-co-curriculum/prototypal-oo-js-using-prototypes
https://github.com/learn-co-curriculum/prototypal-oo-js-object-oriented-object-methods-lab
https://github.com/learn-co-curriculum/prototypal-oo-js-summary

Those are intended to be encountered before the quiz. I've let your instructional team know about this issue and they should clear it up with you.
