### ISSUE TITLE
syntax error in correct answer choice for question 4

### ISSUE THREAD

**Issue by iamtash** [learn-co-curriculum/prototypal-oo-reviewing-javascript-prototypal-inheritance-quiz#3]
In question 4, the most correct answer, `Dog.prototype.bark =  () => console.log(`${this.name} says bark`)` is a bit inaccurate because, by virtue of arrow function syntax, `this` is interpreted as `undefined` and will therefore log ' says bark' to the console

**Comment by sgharms** [comment]
Good catch and a nice demonstration of the power of function expressions over arrow functions. Updated
